### PR TITLE
Fixed MacOS issue

### PR DESCRIPTION
**Pull request by rainergericke**
Applied Header guards.
Option to set shared/static library builds.
Set different names for the library when built in Debug mode. This allows the installation of Release and Debug libraries in the same install prefix.

### CODE REVIEW

**Comment by rainergericke** [comment]
Still need some tests on Windows 11.

**Comment by sum1afk** [comment]
Hey, I saw your fork and request and I wanted to reopen this since it's something I thought might be a useful change and fix
I will look at it again later too
Thanks for the request

**Comment by rainergericke** [comment]
Good news: vsgSDL works on macOS and Windows now. Actually only the static library build can be used on Windows.

**Comment by robertosfield** [comment]
Modern C++ support use of #pragma once on all platforms/compilers so you can avoid the #ifdef/;define/endif blocks around headers. This is what I've done for the VSG and other projects and it keeps the headers clean and functional.

**Pull request closed without merging**
